name: Build & Deploy dev

on:
  push:
    branches:
      - dev
      - feat/fleek
  workflow_dispatch:

env:
  FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Build and Deploy dev branch
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Deploy ğŸš€
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: $FLEEK_API_KEY

      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
